version: '3.1'

services:

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "intern"
    ports:
      - 3307:3306
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:3306"]
    ports:
      - 8080:8080